name: linux-x64

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      BUILD_TYPE: Release

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          wget -q https://github.com/Kitware/CMake/releases/download/v3.30.4/cmake-3.30.4-linux-x86_64.tar.gz
          tar -xf cmake-3.30.4-linux-x86_64.tar.gz
          sudo mv cmake-3.30.4-linux-x86_64 /opt/cmake
          sudo ln -sf /opt/cmake/bin/* /usr/local/bin/

          wget -q https://github.com/ninja-build/ninja/releases/download/v1.12.1/ninja-linux.zip
          unzip -q ninja-linux.zip
          sudo mv ninja /usr/local/bin/ninja
          sudo chmod +x /usr/local/bin/ninja

      - name: Install LLVM
        uses: KyleMayes/install-llvm-action@98e68e10c96dffcb7bfed8b2144541a66b49aa02
        with:
          version: "21.1.3"
          arch: "x64"
          env: true

      - name: Symlinking Libraries
        run: |
          LLVM_LIB_DIR=$(clang++ --print-file-name=libc++.a | xargs dirname)

          cd ${LLVM_LIB_DIR}
          sudo ln -sf libc++.so.1 libc++.so
          sudo ln -sf libunwind.so.1 libunwind.so
          sudo ln -sf libc++abi.so.1 libc++abi.so

          sudo ldconfig
      - name: Building Mint
        run: |
          LLVM_LIB_DIR=$(clang++ --print-file-name=libc++.a | xargs dirname)
          cmake -G Ninja -B build               \
            -DCMAKE_BUILD_TYPE=Release          \
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON  \
            -DCMAKE_CXX_COMPILER=clang++        \
            -DCMAKE_CXX_FLAGS="-stdlib=libc++"  \
            -DCMAKE_EXE_LINKER_FLAGS="-stdlib=libc++ -lc++abi -lunwind -Wl,-rpath,${LLVM_LIB_DIR}"

          ninja -C build -v
      - name: Testing Mint
        run: |
          LLVM_LIB_DIR=$(clang++ --print-file-name=libc++.a | xargs dirname)
          export LD_LIBRARY_PATH="${LLVM_LIB_DIR}:${LD_LIBRARY_PATH}"

          ctest --test-dir build/ --verbose
